# Generated by Django 2.0.2 on 2019-05-17 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PaperInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaperName', models.CharField(max_length=200)),
                ('examdate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('answerA', models.CharField(max_length=200)),
                ('answerB', models.CharField(max_length=200)),
                ('answerC', models.CharField(max_length=200)),
                ('answerD', models.CharField(max_length=200)),
                ('answerR', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Course')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('account', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('Sex', models.CharField(max_length=200)),
                ('Birth', models.DateTimeField(blank=True, null=True)),
                ('Tel', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Addr', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('account', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('Sex', models.CharField(max_length=200)),
                ('Birth', models.DateTimeField(blank=True, null=True)),
                ('Tel', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Addr', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='scoreinfo',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.StudentInfo'),
        ),
        migrations.AddField(
            model_name='scoreinfo',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Course'),
        ),
        migrations.AddField(
            model_name='paperinfo',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.TeacherInfo'),
        ),
    ]
