# Generated by Django 2.0.2 on 2019-05-17 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperinfo',
            name='Pcourse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.Course'),
        ),
        migrations.AddField(
            model_name='scoreinfo',
            name='Spaperinfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.PaperInfo'),
            preserve_default=False,
        ),
    ]
